/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.excella.flajr;

import com.excella.flajr.domain.Flag;
import org.junit.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class FlagrClientIntTest {
    @Test public void testFlagsReturn() {
        FlagrClient client = FlagrClient.create("http://localhost:18000/api/v1");
        List<Flag> listOfAllFlags = client.getAllFlags();

        assertThat(listOfAllFlags).isNotEmpty();
        assertThat(listOfAllFlags)
            .extracting(Flag::getDescription)
            .contains("demo_example");
    }
}
