/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.excella.flajr;

import com.excella.flajr.domain.Flag;
import org.junit.Test;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

public class FlagrIntTest {
    @Test public void testFlagsReturn() {
        Flagr flagr = new Flagr("http://localhost:18000/api/v1");
        List<Flag> listOfAllFlags = flagr.getAllFlags();

        assertThat(listOfAllFlags).isNotEmpty();
        assertThat(listOfAllFlags)
            .extracting(Flag::getDescription)
            .contains("demo_example");
    }

    @Test public void testDemoFlagReturns() {
        Flagr flagr = new Flagr("http://localhost:18000/api/v1");
        Optional<Flag> demoFlag = flagr.getFlag(1);

        assertThat(demoFlag).isNotEmpty();
        assertThat(demoFlag)
            .map(Flag::getDescription)
            .contains("demo_example");
    }
}
