/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.excella.flajr;

import com.excella.flajr.domain.Flag;
import org.junit.Test;

import java.util.List;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;

public class FlagrClientAsyncIntTest {
    @Test public void testFlagsReturn() {
        FlagrClientAsync clientAsync = FlagrClientAsync.create("http://localhost:18000/api/v1");

        clientAsync.getAllFlags()
            .thenAccept(listOfAllFlags -> {
                assertThat(listOfAllFlags).isNotEmpty();
                assertThat(listOfAllFlags)
                    .extracting(Flag::getDescription)
                    .contains("demo_example");
            });
    }
}
